### PR TITLE
DB Bug Fix + Authentication

### LINKED ISSUE #44: DB error causes server to shut down
I noticed that whenever the database threw an error, it would cause the server to shut down. Upon further investigation it seems as though some of the models were accessing properties of those null results. I will pull request a patch soon, but there might be more that I've missed.

### PR DESCRIPTION
**Pull request by shade**
There might be some more ways a failed db might shut down the server. You should check it out.
Resolve #44

### CODE REVIEW

**Comment by schan219** [comment]
Good find! By the way, the master branch is quite behind compared to the sc-authenticator branch so there are some parts of the code from master that you've edited that don't exist anymore. I've fixed the parts that are needed for the backend authentication to work and I'll just merge that before I merge your pull request.

**Comment by schan219** [comment]
Okay, I accidentally polluted this branch with my sc-auth-frontend one, so I probably shouldn't merge to master :/

**Comment by schan219** [comment]
At least not until after sc-auth-frontend has been finished and merged. Sorry about that!

**Comment by shade** [comment]
Haha, no worries, I'll take a look at all the authentication routes once my finals are over.

**Pull request closed without merging**
